import Image from "next/image";
import { createPageMetadata } from "@/app/lib/seo";
import BookingFlow from "./BookingFlow";
import { ClinicButton, ClosingCta, FaqPreview, LocationCards, TreatmentCards, TrustStrip } from "./components/ClinicSections";
import { ClinicPage } from "./components/ClinicShell";

export const metadata = createPageMetadata({
  title: "Modern Dental Care — Tandarts in Amsterdam",
  description: "Persoonlijke tandheelkundige zorg in Amsterdam Oost, Amsterdam West en MDC Junior. Bekijk behandelingen, praktijken en vraag een afspraak aan.",
  path: "/portfolio/modern-dental-care",
});

export default function ModernDentalCarePage() {
  return <ClinicPage>
    <section className="px-5 py-12 md:px-8 lg:px-12 lg:py-20"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="inline-flex items-center gap-2 rounded-full border border-[#173f39]/10 bg-white/70 px-4 py-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#486b63]"><span className="h-1.5 w-1.5 rounded-full bg-[#63aa90]" />Tandheelkunde in Amsterdam</p><h1 className="mt-7 max-w-2xl text-[clamp(3rem,6vw,5.8rem)] font-medium leading-[.94] tracking-[-.065em]">Zorg voor uw gebit, met aandacht voor <span className="font-serif italic font-normal text-[#9a7849]">u.</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-[#5e716c]">Moderne tandheelkunde met duidelijke uitleg, persoonlijke zorg en een rustige ervaring voor het hele gezin.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><ClinicButton href="/portfolio/modern-dental-care/booking">Afspraak maken <span className="ml-2">↗</span></ClinicButton><ClinicButton href="#treatments" secondary>Bekijk behandelingen</ClinicButton></div><p className="mt-7 text-xs leading-5 text-[#7d8e88]">Drie praktijken in Amsterdam · Volwassenen en kinderen · Afspraak aanvragen</p></div><div className="relative overflow-hidden rounded-[36px] shadow-[0_35px_100px_rgba(23,63,57,0.16)]"><Image src="/modern-dental-care/hero.png" alt="Een ontspannen tandartsbezoek bij Modern Dental Care" width={1536} height={1024} priority sizes="(max-width: 1024px) 100vw, 58vw" className="aspect-[4/3] h-full w-full object-cover" /><div className="absolute bottom-5 left-5 rounded-2xl border border-white/35 bg-white/90 p-4 shadow-xl backdrop-blur"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#6e817b]">Modern Dental Care</p><p className="mt-1 text-sm font-semibold">Persoonlijke zorg in Amsterdam</p></div></div></div></section>
    <TrustStrip />
    <section id="treatments" className="px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Behandelingen</p><h2 className="mt-5 max-w-3xl text-4xl font-medium tracking-[-0.05em] sm:text-6xl">Van preventie tot herstel, <span className="font-serif italic font-normal text-[#9a7849]">dichtbij.</span></h2></div><p className="max-w-md text-sm leading-7 text-[#6d7d78]">Ontdek de zorg die bij uw vraag past. Tijdens een afspraak bespreekt het team de mogelijkheden met u.</p></div><div className="mt-12"><TreatmentCards limit={9} /></div><div className="mt-8"><ClinicButton href="/portfolio/modern-dental-care/behandelingen" secondary>Alle behandelingen bekijken <span className="ml-2">↗</span></ClinicButton></div></div></section>
    <section id="why" className="px-5 pb-24 md:px-8 lg:px-12"><div className="mx-auto max-w-[1440px] rounded-[36px] bg-[#173f39] px-7 py-14 text-white sm:px-10 lg:px-16 lg:py-20"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#a6c4b8]">Onze aanpak</p><h2 className="mt-5 max-w-xl text-4xl font-medium tracking-[-0.05em] sm:text-6xl">Zorg voor de mens achter de <span className="font-serif italic font-normal text-[#ddc69d]">glimlach.</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-white/60">Goede tandheelkundige zorg begint met luisteren, helder uitleggen en samen bepalen wat een passende volgende stap is.</p></div><div className="grid gap-3 sm:grid-cols-2">{[["Persoonlijke aandacht","Uw situatie, wensen en vragen staan centraal."],["Preventie als basis","Samen werken aan een gezonde mond op de lange termijn."],["Moderne technieken","Behandelmethoden met duidelijke uitleg vooraf."],["Een rustige ervaring","Aandacht voor comfort, vertrouwen en continuïteit."]].map(([title,text], i) => <article key={title} className="rounded-[24px] border border-white/10 bg-white/[.055] p-6"><span className="text-xs text-[#a6c4b8]">0{i + 1}</span><h3 className="mt-10 text-xl font-medium">{title}</h3><p className="mt-3 text-sm leading-6 text-white/50">{text}</p></article>)}</div></div></div></section>
    <section id="locations" className="border-y border-[#173f39]/10 bg-white px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto max-w-[1440px]"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Onze praktijken</p><h2 className="mt-5 max-w-3xl text-4xl font-medium tracking-[-0.05em] sm:text-6xl">Kies de praktijk die bij u past.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-[#6d7d78]">Bekijk adres, contactgegevens en de eigen sfeer van Amsterdam Oost, Amsterdam West en MDC Junior.</p><div className="mt-12"><LocationCards /></div></div></section>
    <section className="px-5 pt-20 md:px-8 lg:px-12"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-6 rounded-[30px] bg-[#8b3c32] px-7 py-8 text-white sm:px-10 lg:flex-row lg:items-center"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-white/55">Spoed</p><h2 className="mt-2 text-2xl font-medium tracking-[-0.03em]">Acute tandpijn of een ander spoedgeval?</h2><p className="mt-2 text-sm text-white/70">Neem direct telefonisch contact op met de praktijk.</p></div><a href="tel:0204473489" className="inline-flex shrink-0 rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-[#6f2f28]">Bel direct · 020 447 3489</a></div></section>
    <section id="new-patient" className="px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto grid max-w-[1440px] gap-10 rounded-[34px] bg-[#e8eee9] p-8 sm:p-12 lg:grid-cols-[1fr_auto] lg:items-center lg:p-16"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#7c9189]">Nieuwe patiënt</p><h2 className="mt-4 text-4xl font-medium tracking-[-0.05em] sm:text-5xl">Nieuw bij Modern Dental Care?</h2><p className="mt-4 max-w-xl text-sm leading-7 text-[#687a74]">Vraag een eerste afspraak aan. Het team neemt persoonlijk contact op om de volgende stap te bespreken.</p></div><ClinicButton href="/portfolio/modern-dental-care/booking">Afspraak maken <span className="ml-2">↗</span></ClinicButton></div></section>
    <section className="bg-white px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-start"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Veelgestelde vragen</p><h2 className="mt-5 text-4xl font-medium tracking-[-0.05em] sm:text-5xl">Duidelijke antwoorden voor uw bezoek.</h2><a href="/portfolio/modern-dental-care/faq" className="mt-6 inline-flex text-sm font-semibold text-[#326256]">Bekijk alle vragen <span className="ml-2">↗</span></a></div><FaqPreview /></div></section>
    <section id="appointment" className="px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Afspraak aanvragen</p><h2 className="mt-5 text-4xl font-medium tracking-[-0.05em] sm:text-6xl">Van vraag naar afspraak, <span className="font-serif italic font-normal text-[#9a7849]">zonder onnodige stappen.</span></h2><p className="mt-6 max-w-lg text-sm leading-7 text-[#6d7d78]">Kies uw praktijk, vertel ons waar we u mee kunnen helpen en geef uw voorkeur door. De praktijk bevestigt de afspraak persoonlijk.</p></div><BookingFlow /></div></section>
    <ClosingCta title="Een gezonde glimlach begint met persoonlijke aandacht." />
  </ClinicPage>;
}
