import { createPageMetadata } from "@/app/lib/seo";
import LanguageSwitcher from "../../LanguageSwitcher";

export const metadata = createPageMetadata({ title: "Implants — Modern Dental Care | YY Builds", description: "English implant treatment concept page for Modern Dental Care.", path: "/portfolio/modern-dental-care/en/implantaten" });

const steps = [["01", "Consultation", "We discuss your situation, wishes and medical background."], ["02", "Diagnostics", "A careful examination supports a personal treatment plan."], ["03", "Treatment", "The implant treatment is carried out step by step."], ["04", "Aftercare", "Follow-up and guidance support lasting comfort and recovery."]];

export default function EnglishImplantsPage() {
  return <main className="min-h-screen bg-[#f7f5ef] text-[#17332e]"><header className="border-b border-[#173f39]/10"><div className="mx-auto flex min-h-20 max-w-[1360px] items-center justify-between gap-4 px-5 md:px-8 lg:px-12"><a href="/portfolio/modern-dental-care/en" className="text-[12px] font-semibold uppercase tracking-[0.18em]">Modern Dental Care</a><div className="flex items-center gap-2"><LanguageSwitcher current="en" dutchPath="/portfolio/modern-dental-care/implantaten" englishPath="/portfolio/modern-dental-care/en/implantaten" /><a href="/portfolio/modern-dental-care/en/booking" className="rounded-full bg-[#173f39] px-5 py-3 text-xs font-semibold text-white">Book now</a></div></div></header><section className="px-5 py-16 md:px-8 lg:px-12 lg:py-24"><div className="mx-auto max-w-[1200px]"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#7f938c]">Treatment · Implants</p><h1 className="mt-5 max-w-4xl text-5xl font-medium tracking-[-0.055em] sm:text-7xl">A lasting foundation for<span className="block font-serif italic font-normal text-[#9a7849]">a natural smile.</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-[#687a74]">Implants may be an option when one or more teeth are missing. This concept page focuses on trust, clear steps and personal guidance.</p><a href="/portfolio/modern-dental-care/en/booking" className="mt-8 inline-flex rounded-full bg-[#173f39] px-7 py-4 text-sm font-semibold text-white">Request a consultation →</a></div></section><section className="bg-white px-5 py-20 md:px-8 lg:px-12"><div className="mx-auto max-w-[1200px] grid gap-4 md:grid-cols-2">{steps.map(([number, title, text]) => <article key={title} className="rounded-[28px] border border-[#173f39]/10 bg-[#f8f8f3] p-7"><span className="text-xs font-semibold text-[#8aa096]">{number}</span><h2 className="mt-10 text-2xl font-medium">{title}</h2><p className="mt-3 max-w-lg text-sm leading-7 text-[#6d7d78]">{text}</p></article>)}</div></section><section className="px-5 py-20 md:px-8 lg:px-12"><div className="mx-auto max-w-[1200px] rounded-[30px] bg-[#173f39] p-8 text-white sm:p-12"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-white/55">Who may benefit?</p><h2 className="mt-4 text-4xl font-medium tracking-[-0.05em]">A personal assessment comes first.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-white/70">A dentist reviews your oral health and discusses whether an implant could fit your restorative treatment plan.</p></div></section></main>;
}
