import { createPageMetadata } from "@/app/lib/seo";
import { ClinicButton, ClosingCta, FaqPreview, TreatmentCards } from "../components/ClinicSections";
import { ClinicPage } from "../components/ClinicShell";

export const metadata = createPageMetadata({ title: "Behandelingen — Modern Dental Care", description: "Bekijk de behandelingen van Modern Dental Care in Amsterdam, van periodieke controle en mondhygiëne tot herstel en esthetische tandheelkunde.", path: "/portfolio/modern-dental-care/behandelingen" });

export default function TreatmentsPage() {
  return <ClinicPage><section className="px-5 py-20 md:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px]"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Behandelingen</p><h1 className="mt-5 max-w-4xl text-5xl font-medium leading-[.98] tracking-[-.06em] sm:text-7xl">Zorg die past bij uw vraag, <span className="font-serif italic font-normal text-[#9a7849]">uitgelegd in heldere stappen.</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-[#687a74]">Van preventie en mondhygiëne tot herstel, esthetiek en zorg voor kinderen. Tijdens uw afspraak bespreekt het team welke aanpak bij u past.</p><div className="mt-8"><ClinicButton href="/portfolio/modern-dental-care/booking">Afspraak maken <span className="ml-2">↗</span></ClinicButton></div></div></section><section className="bg-white px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto max-w-[1440px]"><TreatmentCards /></div></section><section className="px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Uw eerste stap</p><h2 className="mt-5 text-4xl font-medium tracking-[-0.05em] sm:text-5xl">Niet zeker welke behandeling u nodig heeft?</h2></div><div><p className="max-w-2xl text-sm leading-7 text-[#6d7d78]">Dat is geen probleem. Een controle of eerste gesprek helpt om uw vraag te begrijpen. U krijgt uitleg over de mogelijkheden voordat u een beslissing neemt.</p><ClinicButton href="/portfolio/modern-dental-care/faq" secondary>Veelgestelde vragen bekijken</ClinicButton></div></div></section><section className="bg-white px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto max-w-[900px]"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Patiëntinformatie</p><h2 className="mt-5 text-4xl font-medium tracking-[-0.05em] sm:text-5xl">Een behandelplan begint met aandacht voor uw situatie.</h2><div className="mt-10"><FaqPreview limit={3} /></div></div></section><ClosingCta /></ClinicPage>;
}
