import React from 'react';
import {AbsoluteFill, Sequence, interpolate, useCurrentFrame, useVideoConfig} from 'remotion';
import {BigText, Brand, C, Eyebrow, FinalCard, Icon, Progress, Scene, clamp, enter} from '../components';

const nodes=[{label:'Lead received',sub:'hello@client.co',icon:'mail' as const,color:C.cyan},{label:'AI understands',sub:'Intent · budget · priority',icon:'brain' as const,color:C.violet},{label:'Workflow executes',sub:'Qualify → route → notify',icon:'flow' as const,color:C.lime},{label:'Action complete',sub:'CRM updated · team notified',icon:'check' as const,color:'#65f0a5'}];
const Pipeline=()=>{const f=useCurrentFrame();return <div style={{position:'absolute',top:310,left:70,right:70}}>{nodes.map((n,i)=>{const on=f>i*34;const p=enter(f,30,i*30);return <React.Fragment key={n.label}><div style={{height:145,borderRadius:28,padding:'25px 30px',display:'flex',alignItems:'center',gap:25,opacity:p,transform:`translateX(${(1-p)*80}px)`,background:on?`linear-gradient(110deg,${n.color}18,#11141d)`:'#11141d',border:`1px solid ${on?n.color+'77':'#ffffff13'}`,boxShadow:on?`0 15px 60px ${n.color}15`:'none'}}><div style={{width:70,height:70,borderRadius:20,display:'grid',placeItems:'center',background:n.color+'20',color:n.color}}><Icon name={n.icon} color={n.color}/></div><div><div style={{fontSize:29,fontWeight:800}}>{n.label}</div><div style={{fontSize:18,color:C.muted,marginTop:6}}>{n.sub}</div></div>{on&&<div style={{marginLeft:'auto',fontSize:18,color:n.color}}>● LIVE</div>}</div>{i<3&&<div style={{height:45,width:2,marginLeft:65,background:`linear-gradient(${n.color},${nodes[i+1].color})`,transform:`scaleY(${interpolate(f,[i*34+15,i*34+35],[0,1],clamp)})`,transformOrigin:'top'}}/>}</React.Fragment>})}</div>};

export const AutomationDemo:React.FC=()=> <Scene accent={C.cyan}><Brand/><Sequence durationInFrames={100}><Hook/></Sequence><Sequence from={100} durationInFrames={220}><Flow/></Sequence><Sequence from={320} durationInFrames={130}><Moving/></Sequence><Sequence from={450} durationInFrames={90}><FinalCard title="Automate your business" subtitle="YY Builds — AI • Automation" accent={C.cyan}/></Sequence><Progress color={C.cyan}/></Scene>;
const Hook=()=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const p=enter(f,fps);return <AbsoluteFill style={{justifyContent:'center',padding:70}}><div style={{position:'absolute',right:-80,top:290,width:420,height:420,border:`1px solid ${C.cyan}55`,borderRadius:'50%',transform:`scale(${1+f/300})`,opacity:.5}}/><Eyebrow color={C.cyan}>Your time is valuable</Eyebrow><div style={{opacity:p,transform:`scale(${.9+.1*p})`}}><BigText size={104} accent={C.cyan}>Stop doing<br/>repetitive work<br/>manually.</BigText></div><div style={{marginTop:60,fontSize:23,color:C.muted}}>Let the system handle the busywork.</div></AbsoluteFill>};
const Flow=()=> <AbsoluteFill><div style={{position:'absolute',top:185,left:70}}><Eyebrow color={C.cyan}>Automation / live run</Eyebrow></div><Pipeline/></AbsoluteFill>;
const Moving=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{justifyContent:'center',padding:70}}><Eyebrow color={C.lime}>Always on</Eyebrow><BigText size={96} accent={C.cyan}>Your business<br/>keeps moving.</BigText><div style={{height:150,position:'relative',marginTop:100}}><div style={{position:'absolute',top:69,left:0,right:0,height:2,background:'#ffffff18'}}/>{['Email','AI','n8n','CRM'].map((x,i)=><div key={x} style={{position:'absolute',left:i*250,top:35,width:75,height:75,borderRadius:22,display:'grid',placeItems:'center',background:i===2?C.lime:'#151923',color:i===2?'#071006':C.ink,fontWeight:800,border:'1px solid #ffffff20',transform:`scale(${.92+.08*Math.sin((f-i*7)/8)})`}}>{x}</div>)}<div style={{position:'absolute',top:60,left:`${interpolate(f,[0,110],[0,92],clamp)}%`,width:20,height:20,borderRadius:20,background:C.cyan,boxShadow:`0 0 30px ${C.cyan}`}}/></div></AbsoluteFill>};
