import React from 'react';
import {AbsoluteFill, Sequence, interpolate, useCurrentFrame} from 'remotion';
import {BigText, Brand, C, Eyebrow, FinalCard, Icon, Progress, Scene, clamp, enter} from '../components';

const items=[['Website','Your digital home','web',C.cyan],['AI Agent','Answers. Qualifies. Sells.','brain',C.violet],['Automation','Runs the busywork','flow',C.lime],['Content Engine','Attention on repeat','play','#ff6b9d']] as const;
const System=()=>{const f=useCurrentFrame();return <div style={{position:'absolute',inset:'265px 70px 120px'}}><div style={{position:'absolute',left:'50%',top:505,width:230,height:230,transform:'translate(-50%,-50%)',borderRadius:'50%',background:'radial-gradient(circle,#b6ff5c33,transparent 68%)',display:'grid',placeItems:'center'}}><div style={{width:115,height:115,borderRadius:35,background:C.lime,color:'#071006',display:'grid',placeItems:'center',fontSize:35,fontWeight:800,boxShadow:`0 0 70px ${C.lime}66`,transform:`rotate(${f/4}deg)`}}><span style={{transform:`rotate(${-f/4}deg)`}}>YY</span></div></div>{items.map((it,i)=>{const angle=-Math.PI/2+i*Math.PI/2;const x=50+Math.cos(angle)*39,y=505+Math.sin(angle)*385;const p=enter(f,30,i*14);return <React.Fragment key={it[0]}><div style={{position:'absolute',left:`${x}%`,top:y,width:350,transform:`translate(-50%,-50%) scale(${p})`,padding:'23px 25px',borderRadius:25,background:'#11141dee',border:`1px solid ${it[3]}55`,display:'flex',alignItems:'center',gap:18}}><div style={{color:it[3]}}><Icon name={it[2]} color={it[3]}/></div><div><div style={{fontSize:25,fontWeight:800}}>{it[0]}</div><div style={{fontSize:15,color:C.muted,marginTop:4}}>{it[1]}</div></div></div><svg style={{position:'absolute',inset:0,width:'100%',height:'100%',pointerEvents:'none'}}><line x1="50%" y1="505" x2={`${x}%`} y2={y} stroke={it[3]} strokeOpacity={.35} strokeWidth="2" strokeDasharray="8 10"/></svg></React.Fragment>})}</div>};

export const ContentEngineDemo:React.FC=()=> <Scene accent={C.violet}><Brand/><Sequence durationInFrames={100}><Hook/></Sequence><Sequence from={100} durationInFrames={220}><Connect/></Sequence><Sequence from={320} durationInFrames={130}><Statement/></Sequence><Sequence from={450} durationInFrames={90}><FinalCard title="YY Builds" subtitle="Websites • AI • Automation • Content" accent={C.violet}/></Sequence><Progress color={C.violet}/></Scene>;
const Hook=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{justifyContent:'center',alignItems:'center',textAlign:'center',padding:60}}><div style={{fontSize:20,letterSpacing:5,color:C.muted,marginBottom:35}}>THE CONNECTED BUSINESS</div><div style={{opacity:enter(f,30),transform:`translateY(${(1-enter(f,30))*60}px)`}}><BigText size={111} align="center" accent={C.violet}>One business.<br/>One AI system.</BigText></div><div style={{marginTop:70,display:'flex',gap:10}}>{[0,1,2,3].map(i=><div key={i} style={{width:70,height:5,borderRadius:9,background:f>20+i*7?C.violet:'#ffffff18'}}/>)}</div></AbsoluteFill>};
const Connect=()=>{const f=useCurrentFrame();return <AbsoluteFill><div style={{position:'absolute',top:175,left:70,right:70,display:'flex',justifyContent:'space-between'}}><Eyebrow color={C.violet}>Your growth stack</Eyebrow><span style={{color:C.lime,fontWeight:800,fontSize:20,opacity:interpolate(f,[110,140],[0,1],clamp)}}>CONNECTED ●</span></div><System/></AbsoluteFill>};
const Statement=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{justifyContent:'center',padding:70}}><Eyebrow color={C.violet}>One connected system</Eyebrow><div style={{fontSize:69,fontWeight:700,color:C.muted,letterSpacing:-3}}>More than a website.</div><div style={{marginTop:25}}><BigText size={100} accent={C.lime}>Build a growth<br/>system.</BigText></div><div style={{marginTop:80,height:3,width:`${interpolate(f,[15,95],[0,100],clamp)}%`,background:'linear-gradient(90deg,#7357ff,#52e5ff,#b6ff5c)'}}/></AbsoluteFill>};
