import React from 'react';
import {AbsoluteFill, Sequence, interpolate, useCurrentFrame, useVideoConfig} from 'remotion';
import {BigText, Brand, C, Eyebrow, FinalCard, Icon, Pill, Progress, Scene, clamp, enter} from '../components';

const Browser: React.FC<{modern?:boolean}> = ({modern=false}) => {const f=useCurrentFrame(),{fps}=useVideoConfig();const p=enter(f,fps,4);return <div style={{width:900,height:880,borderRadius:38,overflow:'hidden',background:modern?'#0d111a':'#e7e5df',border:`1px solid ${modern?'#ffffff22':'#7774'}`,boxShadow:modern?'0 50px 130px #000, 0 0 70px #7357ff33':'0 35px 80px #0008',transform:`translateY(${(1-p)*120}px) scale(${.88+.12*p}) rotateX(${(1-p)*8}deg)`}}>
 <div style={{height:76,display:'flex',alignItems:'center',gap:12,padding:'0 26px',background:modern?'#151923':'#cac7c0'}}><i style={{width:13,height:13,borderRadius:99,background:'#ff6b6b'}}/><i style={{width:13,height:13,borderRadius:99,background:'#ffd75c'}}/><i style={{width:13,height:13,borderRadius:99,background:'#6bdd91'}}/><div style={{marginLeft:15,height:35,flex:1,borderRadius:10,background:modern?'#080a10':'#eee',color:'#777',padding:'8px 18px',fontSize:14}}>yourbusiness.com</div></div>
 {modern?<div style={{padding:45,color:C.ink,position:'relative',height:804,background:'radial-gradient(circle at 80% 30%,#7357ff3a,transparent 37%)'}}><div style={{display:'flex',justifyContent:'space-between',fontWeight:800,fontSize:17}}><span>MONO<span style={{color:C.lime}}>+</span></span><span style={{color:C.muted}}>WORK · ABOUT · CONTACT</span></div><div style={{marginTop:105,width:700,fontSize:69,lineHeight:.95,fontWeight:800,letterSpacing:-4}}>Ideas that move<br/><span style={{color:C.lime}}>business forward.</span></div><div style={{color:C.muted,fontSize:20,width:510,lineHeight:1.5,marginTop:30}}>Sharp strategy. Beautiful digital products. Built for ambitious teams.</div><button style={{marginTop:38,border:0,borderRadius:99,padding:'18px 27px',fontWeight:800,background:C.lime}}>START A PROJECT ↗</button><div style={{position:'absolute',right:45,bottom:44,left:45,display:'flex',gap:12}}>{['98 Performance','Mobile first','2.4× Conversion'].map(x=><div key={x} style={{flex:1,padding:17,borderRadius:15,background:'#ffffff09',fontSize:15,color:C.muted}}>{x}</div>)}</div></div>:
 <div style={{padding:34,color:'#45433e',fontFamily:'serif'}}><div style={{fontWeight:'bold',fontSize:25}}>ACME SERVICES INC.</div><div style={{fontSize:15,textDecoration:'underline',marginTop:8}}>Home | About Us | Our Services | Contact</div><div style={{height:220,marginTop:30,background:'#bbb8b0',display:'grid',placeItems:'center',color:'#777'}}>IMAGE NOT FOUND</div><div style={{fontSize:36,fontWeight:'bold',marginTop:30}}>Welcome To Our Website</div><p style={{fontSize:18,lineHeight:1.2}}>We are a company that provides quality solutions. Please browse our website to learn more about all of our services.</p><button style={{padding:8,fontSize:15}}>CLICK HERE</button></div>}
 </div>};

export const WebsiteDemo: React.FC = () => <Scene accent={C.violet}><Brand/><Sequence durationInFrames={105}><Hook/></Sequence><Sequence from={105} durationInFrames={115}><Weak/></Sequence><Sequence from={220} durationInFrames={125}><Transform/></Sequence><Sequence from={345} durationInFrames={105}><Proof/></Sequence><Sequence from={450} durationInFrames={90}><FinalCard title="Build better with YY Builds" subtitle="Websites designed to earn attention."/></Sequence><Progress/></Scene>;

const Hook=()=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const p=enter(f,fps);return <AbsoluteFill style={{justifyContent:'center',padding:70}}><Eyebrow>01 / The hard truth</Eyebrow><div style={{transform:`translateY(${(1-p)*70}px)`,opacity:p}}><BigText size={108}>Your business is<br/>losing clients<br/><span style={{color:C.lime}}>online.</span></BigText></div><div style={{marginTop:55,width:220,height:7,borderRadius:9,background:'#ffffff15'}}><div style={{width:`${interpolate(f,[15,65],[0,100],clamp)}%`,height:'100%',background:C.lime}}/></div></AbsoluteFill>};
const Weak=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{alignItems:'center',paddingTop:210}}><div style={{opacity:interpolate(f,[0,14,100,115],[0,1,1,0],clamp),transform:`translateX(${Math.sin(f*.7)*2}px)`}}><Browser/></div><div style={{position:'absolute',left:70,bottom:100}}><BigText size={72}>Slow. Outdated.<br/><span style={{color:'#ff716b'}}>Forgettable.</span></BigText></div></AbsoluteFill>};
const Transform=()=>{const f=useCurrentFrame();const wipe=interpolate(f,[15,70],[0,100],clamp);return <AbsoluteFill style={{alignItems:'center',paddingTop:230}}><div style={{position:'absolute',top:150,left:70}}><Eyebrow color={C.cyan}>The transformation</Eyebrow><BigText size={67}>Turn it into an experience.</BigText></div><div style={{marginTop:260,clipPath:`inset(0 ${100-wipe}% 0 0 round 38px)`}}><Browser modern/></div><div style={{position:'absolute',left:`${wipe}%`,top:480,bottom:170,width:3,background:C.lime,boxShadow:`0 0 35px ${C.lime}`}}/></AbsoluteFill>};
const Proof=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{justifyContent:'center',padding:70}}><Eyebrow>Built for results</Eyebrow><BigText size={90}>Fast <span style={{color:C.lime}}>•</span> Modern<br/>Built to convert</BigText><div style={{display:'flex',gap:14,marginTop:60}}>{['98 speed','Mobile-first','Trust by design'].map((x,i)=><div key={x} style={{opacity:enter(f,30,i*8),transform:`translateY(${(1-enter(f,30,i*8))*30}px)`}}><Pill active={i===0}>{x}</Pill></div>)}</div><div style={{marginTop:100,display:'flex',gap:30,alignItems:'center',color:C.muted,fontSize:22}}><Icon name="web" color={C.cyan}/><span>A better first impression, in every scroll.</span></div></AbsoluteFill>};
