import { createPageMetadata } from "@/app/lib/seo";
import LanguageSwitcher from "../../LanguageSwitcher";

export const metadata = createPageMetadata({ title: "MDC Junior — Modern Dental Care | YY Builds", description: "English pediatric dentistry concept page for MDC Junior.", path: "/portfolio/modern-dental-care/en/mdc-junior" });

const principles = [["A calm introduction", "Children get time to become familiar with the environment and the team."], ["Clear explanations", "We explain each step in language children can understand."], ["A positive routine", "A good experience helps build healthy habits for later."]];

export default function EnglishMdcJuniorPage() {
  return <main className="min-h-screen bg-[#fff9ef] text-[#17332e]"><header className="border-b border-[#173f39]/10"><div className="mx-auto flex min-h-20 max-w-[1360px] items-center justify-between gap-4 px-5 md:px-8 lg:px-12"><a href="/portfolio/modern-dental-care/en" className="text-[12px] font-semibold uppercase tracking-[0.18em]">Modern Dental Care</a><div className="flex items-center gap-2"><LanguageSwitcher current="en" dutchPath="/portfolio/modern-dental-care/mdc-junior" englishPath="/portfolio/modern-dental-care/en/mdc-junior" /><a href="/portfolio/modern-dental-care/en/booking" className="rounded-full bg-[#173f39] px-5 py-3 text-xs font-semibold text-white">Book now</a></div></div></header><section className="px-5 py-16 md:px-8 lg:px-12 lg:py-24"><div className="mx-auto max-w-[1280px]"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#8f9f92]">MDC Junior</p><h1 className="mt-5 max-w-4xl text-5xl font-medium tracking-[-0.055em] sm:text-7xl">A positive start for<span className="block font-serif italic font-normal text-[#c08756]">little smiles.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-[#6f7f77]">A calm, child-friendly approach helps children feel comfortable with dental care.</p><a href="/portfolio/modern-dental-care/en/booking" className="mt-8 inline-flex rounded-full bg-[#173f39] px-7 py-4 text-sm font-semibold text-white">Book for my child →</a></div></section><section className="bg-white px-5 py-20 md:px-8 lg:px-12"><div className="mx-auto max-w-[1280px]"><h2 className="text-4xl font-medium tracking-[-0.05em] sm:text-5xl">Calm, trust and a positive experience.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{principles.map(([title, text], i) => <article key={title} className="rounded-[28px] border border-[#173f39]/10 bg-[#fff9ef] p-7"><span className="text-xs font-semibold text-[#a2967e]">0{i + 1}</span><h3 className="mt-10 text-2xl font-medium">{title}</h3><p className="mt-3 text-sm leading-7 text-[#6f7f77]">{text}</p></article>)}</div></div></section><section className="px-5 py-20 md:px-8 lg:px-12"><div className="mx-auto max-w-[1280px] rounded-[34px] bg-[#173f39] p-8 text-white sm:p-12"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-white/55">For parents</p><h2 className="mt-4 max-w-3xl text-4xl font-medium tracking-[-0.05em] sm:text-5xl">Would you like to plan an appointment for your child?</h2><a href="/portfolio/modern-dental-care/en/booking" className="mt-7 inline-flex rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-[#173f39]">Request an appointment →</a></div></section></main>;
}
