import { createPageMetadata } from "@/app/lib/seo";
import { ClinicButton, ClosingCta, FaqPreview, TreatmentCards } from "../components/ClinicSections";
import { ClinicPage } from "../components/ClinicShell";

export const metadata = createPageMetadata({ title: "Implantaten — Modern Dental Care", description: "Lees hoe een implantaattraject bij Modern Dental Care kan worden opgebouwd met duidelijke stappen en persoonlijke begeleiding.", path: "/portfolio/modern-dental-care/implantaten" });

const steps = [["Consultatie", "We bespreken uw situatie, wensen en relevante achtergrond."], ["Diagnostiek", "Een zorgvuldig onderzoek ondersteunt een persoonlijk behandelplan."], ["Behandeling", "Het traject wordt stap voor stap en met duidelijke uitleg uitgevoerd."], ["Nazorg", "Controle en begeleiding blijven onderdeel van een zorgvuldig traject."]];

export default function ImplantatenPage() { return <ClinicPage><section className="px-5 py-20 md:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px]"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Behandeling · Herstel</p><h1 className="mt-5 max-w-4xl text-5xl font-medium leading-[.98] tracking-[-0.06em] sm:text-7xl">Een duurzame basis voor <span className="font-serif italic font-normal text-[#9a7849]">een natuurlijke glimlach.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#687a74]">Implantaten kunnen een oplossing zijn wanneer één of meerdere tanden ontbreken. Een persoonlijk gesprek en zorgvuldig onderzoek vormen de basis voor een passend traject.</p><div className="mt-8"><ClinicButton href="/portfolio/modern-dental-care/booking">Consultatie aanvragen <span className="ml-2">↗</span></ClinicButton></div></div></section><section className="bg-white px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto max-w-[1200px]"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Het traject</p><div className="mt-10 grid gap-4 md:grid-cols-2">{steps.map(([title,text], index) => <article key={title} className="rounded-[28px] border border-[#173f39]/10 bg-[#f8f8f3] p-7"><span className="text-xs font-semibold text-[#8aa096]">0{index + 1}</span><h2 className="mt-10 text-2xl font-medium">{title}</h2><p className="mt-3 text-sm leading-7 text-[#6d7d78]">{text}</p></article>)}</div></div></section><section className="px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto grid max-w-[1200px] gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Voor wie?</p><h2 className="mt-4 text-4xl font-medium tracking-[-0.05em] sm:text-5xl">Wanneer kan een implantaat passen?</h2></div><div className="rounded-[30px] bg-[#173f39] p-8 text-white"><ul className="space-y-5 text-sm leading-7 text-white/75"><li>• Bij het ontbreken van één of meerdere tanden.</li><li>• Wanneer comfort en stabiliteit belangrijk zijn.</li><li>• Als onderdeel van een persoonlijk restauratief behandelplan.</li><li>• Na beoordeling door een tandarts op basis van uw mondgezondheid.</li></ul></div></div></section><section className="bg-white px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto grid max-w-[1200px] gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Uw vragen</p><h2 className="mt-4 text-4xl font-medium tracking-[-0.05em]">Een goed gesprek begint bij uw situatie.</h2></div><FaqPreview limit={3} /></div></section><section className="px-5 py-24 md:px-8 lg:px-12"><div className="mx-auto max-w-[1200px]"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Gerelateerde zorg</p><div className="mt-8"><TreatmentCards limit={3} /></div></div></section><ClosingCta title="Bespreek rustig wat voor u mogelijk is." /></ClinicPage>; }
