import Image from "next/image";
import { createPageMetadata } from "@/app/lib/seo";
import { ClinicButton, ClosingCta, TreatmentCards } from "../components/ClinicSections";
import { ClinicPage } from "../components/ClinicShell";
import { locations } from "../data";

export const metadata = createPageMetadata({ title: "Amsterdam Oost — Modern Dental Care", description: "Bekijk de praktijkgegevens en tandheelkundige zorg van Modern Dental Care Amsterdam Oost.", path: "/portfolio/modern-dental-care/amsterdam-oost" });

export default function AmsterdamOostPage() { const location = locations[0]; return <ClinicPage><section className="px-5 py-16 md:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Praktijk · Amsterdam Oost</p><h1 className="mt-5 text-5xl font-medium leading-[.98] tracking-[-.06em] sm:text-7xl">Persoonlijke tandheelkunde in <span className="font-serif italic font-normal text-[#9a7849]">Amsterdam Oost.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-[#687a74]">{location.description} Moderne tandheelkundige zorg met duidelijke uitleg en aandacht voor iedere patiënt.</p><div className="mt-8 flex flex-wrap gap-3"><ClinicButton href="/portfolio/modern-dental-care/booking">Afspraak aanvragen</ClinicButton><ClinicButton href={location.phoneHref} secondary>{location.phone}</ClinicButton></div><div className="mt-10 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white p-5"><p className="text-xs text-[#7f938c]">Adres</p><p className="mt-2 text-sm font-semibold">{location.address}</p><p className="text-sm">{location.postalCode}</p></div><div className="rounded-2xl bg-white p-5"><p className="text-xs text-[#7f938c]">Telefoon</p><a href={location.phoneHref} className="mt-2 block text-sm font-semibold">{location.phone}</a></div><div className="rounded-2xl bg-white p-5"><p className="text-xs text-[#7f938c]">Opening</p><p className="mt-2 text-sm font-semibold">{location.hours}</p></div></div></div><div className="overflow-hidden rounded-[36px] shadow-[0_35px_100px_rgba(23,63,57,0.14)]"><Image src="/modern-dental-care/hero.png" alt="Modern Dental Care Amsterdam Oost" width={1536} height={1024} sizes="(max-width: 1024px) 100vw, 55vw" className="aspect-[4/3] w-full object-cover" /></div></div></section><section className="bg-white px-5 py-20 md:px-8 lg:px-12"><div className="mx-auto max-w-[1440px]"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#82928d]">Beschikbare zorg</p><h2 className="mt-4 text-4xl font-medium tracking-[-0.05em] sm:text-5xl">Veel behandelingen onder één dak.</h2><div className="mt-10"><TreatmentCards limit={9} /></div></div></section><ClosingCta title="Klaar voor uw volgende afspraak?" /></ClinicPage>; }
